#!/bin/sh
# Copyright 2026 Erik Ben Heckman <erik@heckman.ca>
# spdx-license-identifier: MIT
#
#   photos-selection -- version 0.0.2
#
# prints a json array of the media items
# currently selected in the Photos Application.
#
# requires Hammerspoon <https://www.hammerspoon.org>
# and the PhotosServer Spoon
#   <https://github.com/heckman/PhotosServer.spoon>
#
# and any posixish awk.

default_limit=1000

readonly usage="
Usage: photos-selection [limit]

       Prints a json array to stdout of the media items
       currently selected in the Photos Application.

       It will only print the properties for the first
       'limit' selected items. Default is $default_limit.
       Specify 0 to remove the limit, but be warned, my
       library of ~55k items takes 11 minutes to process.

"

case "$1" in
	--help|-h)
		echo "$usage"
		exit 0
		;;
        '')
		map="limitedMap($default_limit,properties)"
		;;
	0)
		map="map(properties)"
		;;
	*[!0123456789]*)
		echo "Error: limit must be an integer." >&2
		echo "$usage" >&2
		exit 1
		;;
	*)
		map="limitedMap($1,properties)"
		;;
esac

# timeout after 15 mintutes (my libary of 55k items takes 11 minutes)
hs -q -t 900 -c "
hs.json.encode(
	(function(jxa)
		local result, err = hs.loadSpoon'Photos'.jxa(jxa)
		return result and result or err
	end)('selection().$map'),
	true
)
" |
awk ' # valid output begins with [
NR==1 && /^[^[]/ {
	err=1
}
{
	if (err) { print | "cat 1>&2" } else { print }
}
END {
	if (err) exit 1
}
'
